In [5]:
import pandas as pd
import numpy as np

Precios en centavos de dolar por libra

In [20]:
precios = pd.read_csv('../Data anual/Precios.csv')
print(precios.info())
precios.tail(15)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 303 entries, 0 to 302
Data columns (total 5 columns):
 #   Column                                   Non-Null Count  Dtype
---  ------                                   --------------  -----
 0   Mes                                      303 non-null    object
 1   Fecha                                    303 non-null    object
 2   Precio_indicador_compuesto_OIC_US_Cents  303 non-null    float64
 3   Nueva_York_US_Cents                      303 non-null    float64
 4   Europa_US_Cents                          303 non-null    float64
dtypes: float64(3), object(2)
memory usage: 12.0+ KB
None

,Mes,Fecha,Precio_indicador_compuesto_OIC_US_Cents,Nueva_York_US_Cents,Europa_US_Cents
288,ene-25,2025-01-01,310.12,351.46,352.59
289,feb-25,2025-02-01,354.32,408.81,413.17
290,mar-25,2025-03-01,347.85,402.65,408.18
291,abr-25,2025-04-01,335.76,392.81,395.97
292,may-25,2025-05-01,334.41,394.49,397.12
293,jun-25,2025-06-01,295.06,360.02,360.16
294,jul-25,2025-07-01,259.31,323.13,321.31
295,ago-25,2025-08-01,297.05,369.14,363.39
296,sep-25,2025-09-01,324.62,407.09,399.18
297,oct-25,2025-10-01,326.38,404.35,401.73
298,nov-25,2025-11-01,330.44,409.89,407.19
299,dic-25,2025-12-01,304.68,383.85,380.22
300,ene-26,2026-01-01,296.89,374.85,367.10
301,feb-26,2026-02-01,267.57,335.82,324.09
302,mar-26,2026-03-01,273.70,340.34,333.46

In [21]:
predicciones = pd.read_excel('../Data anual/total_pred_final.xlsx')
print(predicciones.info())
predicciones.head(20)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 426 entries, 0 to 425
Data columns (total 6 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Year                  426 non-null    int64
 1   Mpio                  426 non-null    object
 2   Rendimiento           426 non-null    float64
 3   Rendimiento_Predicho  426 non-null    float64
 4   Error                 426 non-null    float64
 5   Abs_Error             426 non-null    float64
dtypes: float64(4), int64(1), object(1)
memory usage: 20.1+ KB
None

,Year,Mpio,Rendimiento,Rendimiento_Predicho,Error,Abs_Error
0,2007,MONIQUIRA_BOYACA,1.000000,0.939594,0.060406,0.060406
1,2008,MONIQUIRA_BOYACA,1.000000,0.919221,0.080779,0.080779
2,2009,MONIQUIRA_BOYACA,0.990000,0.931683,0.058317,0.058317
3,2010,MONIQUIRA_BOYACA,0.650000,0.819406,-0.169406,0.169406
4,2011,MONIQUIRA_BOYACA,0.668693,0.729976,-0.061283,0.061283
5,2012,MONIQUIRA_BOYACA,1.000000,0.896038,0.103962,0.103962
6,2013,MONIQUIRA_BOYACA,0.640093,0.683742,-0.043649,0.043649
7,2014,MONIQUIRA_BOYACA,0.692126,0.788489,-0.096363,0.096363
8,2015,MONIQUIRA_BOYACA,0.899531,1.066163,-0.166632,0.166632
9,2016,MONIQUIRA_BOYACA,0.930295,0.907958,0.022337,0.022337
10,2017,MONIQUIRA_BOYACA,0.842666,0.892488,-0.049822,0.049822
11,2018,MONIQUIRA_BOYACA,0.861884,0.950748,-0.088863,0.088863
12,2019,MONIQUIRA_BOYACA,1.234717,1.077886,0.156831,0.156831
13,2020,MONIQUIRA_BOYACA,1.141384,1.107919,0.033465,0.033465
14,2021,MONIQUIRA_BOYACA,1.040002,1.060698,-0.020696,0.020696
15,2022,MONIQUIRA_BOYACA,0.853683,0.856881,-0.003197,0.003197
16,2023,MONIQUIRA_BOYACA,0.763712,0.901355,-0.137644,0.137644
17,2024,MONIQUIRA_BOYACA,0.940667,0.836385,0.104282,0.104282
18,2007,SAN JOSE DE PARE_BOYACA,1.000000,0.944804,0.055196,0.055196
19,2008,SAN JOSE DE PARE_BOYACA,1.100000,0.901806,0.198194,0.198194

Se calcula el corte del threshold: 1 desviacion estandar por debajo del promedio de rendimiento total, sin contar el ultimo año.

In [22]:
predicciones_mpio_avg = predicciones[predicciones['Year'] != 2024].groupby('Mpio', as_index=False)['Rendimiento'].mean()
predicciones_mpio_avg.rename(columns={'Rendimiento': 'Rendimiento_avg'}, inplace=True)
predicciones_mpio_avg['Std'] = predicciones.groupby('Mpio')['Rendimiento'].std().values
predicciones_mpio_avg['Std_thresh_1'] = predicciones_mpio_avg['Rendimiento_avg'] - predicciones_mpio_avg['Std']
predicciones_mpio_avg['Std_thresh_2'] = predicciones_mpio_avg['Rendimiento_avg'] - predicciones_mpio_avg['Std']*2
predicciones_mpio_avg

,Mpio,Rendimiento_avg,Std,Std_thresh_1,Std_thresh_2
0,AGUADA_SANTANDER,0.973456,0.440875,0.532580,0.091705
1,BARBOSA_SANTANDER,1.107032,0.222439,0.884593,0.662153
2,CHARALA_SANTANDER,0.999516,0.225404,0.774112,0.548708
3,CHIPATA_SANTANDER,0.947795,0.365098,0.582697,0.217599
4,CONFINES_SANTANDER,0.889573,0.268010,0.621562,0.353552
5,CURITI_SANTANDER,0.984168,0.319372,0.664796,0.345423
6,EL SOCORRO_SANTANDER,1.000569,0.215656,0.784914,0.569258
7,GUADALUPE_SANTANDER,0.934475,0.285402,0.649072,0.363670
8,GUAPOTA_SANTANDER,1.009443,0.258427,0.751016,0.492589
9,GUEPSA_SANTANDER,1.010127,0.276349,0.733778,0.457430
10,MONIQUIRA_BOYACA,0.894635,0.168498,0.726136,0.557638
11,OCAMONTE_SANTANDER,1.078662,0.221712,0.856950,0.635238
12,OIBA_SANTANDER,0.958786,0.215612,0.743174,0.527562
13,PALMAS DEL SOCORRO_SANTANDER,1.010815,0.259946,0.750868,0.490922
14,PARAMO_SANTANDER,1.036245,0.300588,0.735657,0.435069
15,PINCHOTE_SANTANDER,0.976468,0.246323,0.730145,0.483821
16,PUENTE NACIONAL_SANTANDER,0.862056,0.393518,0.468538,0.075020
17,SAN BENITO_SANTANDER,0.952352,0.390476,0.561877,0.171401
18,SAN GIL_SANTANDER,0.890258,0.320215,0.570043,0.249827
19,SAN JOSE DE PARE_BOYACA,0.966260,0.210508,0.755751,0.545243
20,SANTANA_BOYACA,0.678852,0.300712,0.378139,0.077427
21,SUAITA_SANTANDER,0.980746,0.282143,0.698602,0.416459
22,TOGUI_BOYACA,0.949635,0.194020,0.755615,0.561595
23,VALLE DE SAN JOSE_SANTANDER,1.116128,0.364994,0.751134,0.386140

## Función de cálculo